stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

# Cache dependencies between jobs
cache:
  paths:
    - packages/frontend/node_modules/
    - packages/backend/node_modules/

# Build frontend
build-frontend:
  stage: build
  image: node:20-alpine
  script:
    - cd packages/frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - packages/frontend/dist/

# Build backend
build-backend:
  stage: build
  image: node:20-alpine
  script:
    - cd packages/backend
    - npm install
    - npm run build
  artifacts:
    paths:
      - packages/backend/dist/

# Test frontend
test-frontend-lint:
  stage: test
  image: node:20-alpine
  script:
    - cd packages/frontend
    - npm install
    - npm run lint
  only:
    - main

# Test backend
test-backend-lint:
  stage: test
  image: node:20-alpine
  script:
    - cd packages/backend
    - npm install
    - npm run lint
  only:
    - main

# Deploy to production
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$SSH_KNOWN_HOSTS" | tr -d '\r' | base64 -d > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add ~/.ssh/id_rsa
  script:
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd /var/www/farmtrack && git pull origin main && docker compose -f docker-compose.production.yml up --build -d"
  only:
    - main
  when: manual 