services:
  frontend:
    container_name: farmtrack-frontend
    build:
      context: ./packages/frontend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://cscloud7-138.lnu.se/api
    ports:
      - "5173:5173"

  backend:
    container_name: farmtrack-backend
    build:
      context: ./packages/backend
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"

  mongodb:
    container_name: farmtrack-mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
