services:
  frontend:
    container_name: farmtrack-frontend
    build:
      context: ./packages/frontend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://cscloud7-138.lnu.se/api
    ports:
      - "5173:5173"

  backend:
    container_name: farmtrack-backend
    build:
      context: ./packages/backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI_BASE=${MONGODB_URI_BASE}
      - MONGODB_URI_PARAMS=${MONGODB_URI_PARAMS}
      - JWT_SECRET=${JWT_SECRET}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "5000:5000"

  mongodb:
    container_name: farmtrack-mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
