version: '3.8'

services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    volumes:
      - ./packages/frontend/src:/usr/src/app/src:cached
      - ./packages/frontend/public:/usr/src/app/public:cached
      - ./packages/frontend/index.html:/usr/src/app/index.html:cached
      - ./packages/frontend/vite.config.js:/usr/src/app/vite.config.js:cached
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    volumes:
      - ./packages/backend/src:/usr/src/app/src:cached
      - ./packages/backend/nodemon.json:/usr/src/app/nodemon.json:cached
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=5000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
