version: '3.8'

services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.production
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "80:80"

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.production
    environment:
      - NODE_ENV=production
    restart: unless-stopped
